/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SpeedNumber1;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.InputStream;
import java.util.Random;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author hai
 */
public class MainFrame extends javax.swing.JFrame {
private Timer timer;
int giay = 0, khac = 0;
String str3, correct, timing;
String soundName;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resource/Brain"));
        setIconImage(icon);
        setLocationRelativeTo(null);
    }
    public void close(){
        WindowEvent winClose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClose);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgRecall = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        tfRecall = new javax.swing.JTextField();
        lbReview = new javax.swing.JLabel();
        dlgResult = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        lbCom = new javax.swing.JLabel();
        lbCorrect = new javax.swing.JLabel();
        lbTiming = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfStr3 = new javax.swing.JTextField();
        btnGo = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();

        dlgRecall.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgRecall.setTitle("Type to recall");
        dlgRecall.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        dlgRecall.setLocation(new java.awt.Point(320, 260));
        dlgRecall.setResizable(false);
        dlgRecall.setSize(new java.awt.Dimension(375, 250));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        tfRecall.getDocument().addDocumentListener(new MyDoLi());
        tfRecall.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfRecall.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfRecall.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tfRecall.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfRecall.setFocusCycleRoot(true);
        tfRecall.setFocusTraversalPolicyProvider(true);

        lbReview.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbReview.setForeground(new java.awt.Color(255, 0, 0));
        lbReview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfRecall, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(lbReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbReview, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgRecallLayout = new javax.swing.GroupLayout(dlgRecall.getContentPane());
        dlgRecall.getContentPane().setLayout(dlgRecallLayout);
        dlgRecallLayout.setHorizontalGroup(
            dlgRecallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgRecallLayout.setVerticalGroup(
            dlgRecallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dlgResult.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgResult.setLocation(new java.awt.Point(320, 0));
        dlgResult.setResizable(false);
        dlgResult.setSize(new java.awt.Dimension(375, 230));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        lbCom.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        lbCom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCom.setText("Challenge is still there!");

        lbCorrect.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lbCorrect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbTiming.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lbTiming.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnOK.setBackground(new java.awt.Color(0, 255, 204));
        btnOK.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        btnOK.setText("Continue");
        btnOK.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnQuit.setBackground(new java.awt.Color(0, 255, 204));
        btnQuit.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbCom, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                            .addComponent(lbCorrect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTiming, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbCom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTiming, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgResultLayout = new javax.swing.GroupLayout(dlgResult.getContentPane());
        dlgResult.getContentPane().setLayout(dlgResultLayout);
        dlgResultLayout.setHorizontalGroup(
            dlgResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgResultLayout.setVerticalGroup(
            dlgResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Speed Number");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 375, 250));
        setMinimumSize(new java.awt.Dimension(375, 250));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 250));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel1.setText("Can you remember 18 numbers within 7s?");

        tfStr3.setEditable(false);
        tfStr3.setBackground(new java.awt.Color(255, 255, 255));
        tfStr3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfStr3.setForeground(new java.awt.Color(204, 204, 204));
        tfStr3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStr3.setText("Remerber this");
        tfStr3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnGo.setBackground(new java.awt.Color(0, 255, 204));
        btnGo.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        btnGo.setText("Go");
        btnGo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(0, 255, 204));
        btnStop.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        btnStop.setText("Stop");
        btnStop.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnStop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfStr3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfStr3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        btnGo.setEnabled(false);
        timerDemo();
        timer.start();
        Random();
        btnStop.setEnabled(true);
        
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        timer.stop();
        close();
        dlgRecall.setVisible(true);
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        dlgRecall.setVisible(false);
        dlgResult.setVisible(false);
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    

    
public void playSound(String soundName){
   try{
       InputStream in = getClass().getResourceAsStream("/resource/"+soundName);
       AudioStream as = new AudioStream(in);
       AudioPlayer.player.start(as);
   }
   catch(Exception e){
       e.printStackTrace();
   }
}
   
public void Random(){
          Random r = new Random();
        int a = 100000000 +r.nextInt(900000000);
        String strA = String.valueOf(a);
        int b = 100000000 + r.nextInt(900000000);
        String strB = String.valueOf(b);
        str3 = strA.concat(strB);
        tfStr3.setForeground(java.awt.Color.black);
        tfStr3.setText(str3);
    }

public void timerDemo(){
    timer = new Timer(10, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
          khac++;
          if(khac == 100){
              khac = 0;
              giay++;
              playSound("woodclock.wav");
              if(giay == 30){
                  timer.stop();
                  close();
                  dlgRecall.setVisible(true);
              }  
          }          
        }
    });
}

class MyDoLi implements DocumentListener{

        @Override
        public void insertUpdate(DocumentEvent de) {
            change();
        }

        @Override
        public void removeUpdate(DocumentEvent de) {
    
        }

        @Override
        public void changedUpdate(DocumentEvent de) {
           
        }
    public void change(){       
        int index = tfRecall.getText().length();
        String str1 = str3.charAt(index-1)+"";
        String str2 = tfRecall.getText().substring(index-1)+"";
        
        if(str1.equals(str2)){
            playSound("Type.wav");
            if(index == 18){  
                Comment();
                lbCorrect.setText("Correct :    "+index+"/18");                
                if(giay<7){
                    playSound("vo_tay.wav");
                    lbCom.setText("You did it");
                }
            }
        }
        else{
            playSound("Eee.WAV");
            Comment();
            lbCorrect.setText("Correct :    "+(index-1)+"/18"); 
        }
    }
}

public void Comment(){
    tfRecall.setEditable(false);
    lbReview.setText(str3);
    dlgResult.setVisible(true);
    lbTiming.setText("Timing  :    "+giay+":"+khac);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnStop;
    private javax.swing.JDialog dlgRecall;
    private javax.swing.JDialog dlgResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbCom;
    private javax.swing.JLabel lbCorrect;
    private javax.swing.JLabel lbReview;
    private javax.swing.JLabel lbTiming;
    private javax.swing.JTextField tfRecall;
    private javax.swing.JTextField tfStr3;
    // End of variables declaration//GEN-END:variables
}
